name: Feature Request
description: Proposer une nouvelle fonctionnalité
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème
      description: Quel besoin n'est pas couvert ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
